import fs from 'node:fs';
import {uiContent as old} from './dist/uiContent.js';
let source=fs.readFileSync('dist/app.js','utf8');
source=source.replace("import {uiContent as UI} from './uiContent.js';\n",'').replace(/UI\.text\d+/g,key=>"'"+old[key.slice(3)]+"'");
const copy={};let count=0;
source=source.replace(/'((?:\\.|[^'\\])*)'/g,(raw,value)=>{if(!value.includes('|')||value==='|')return raw;const key=`text${++count}`;copy[key]=value;return `UI.${key}`;});
source="import {uiContent as UI} from './uiContent.js';\n"+source;
fs.writeFileSync('dist/app.js',source);
fs.writeFileSync('dist/uiContent.js','// All interface copy: English | Português.\nexport const uiContent = '+JSON.stringify(copy,null,2)+';\n');
console.log(`${count} interface strings centralized`);
